### PR TITLE
Hb body

### PR DESCRIPTION
**Pull request by heavenburdette1988**
You will see a final product.
Please review changes and check if we can  be approved.

### CODE REVIEW

**Comment by helloamandaball** [comment]
- Update background on Germany.

**Comment by heavenburdette1988** [comment]
Let's try again

**Comment by nicholasvperry** [comment]
Looks perfect!

**Comment by heavenburdette1988** [comment]
third time is a charm

**Comment by helloamandaball** [comment]
- looks good. just needed google font @import added to Scotland.html

**Comment by helloamandaball** [comment]
- @import added to scotland.html looks okay now. (thumbs up)

**Comment by nicholasvperry** [comment]
Looks great!

**Pull request merged**
